Repository NordicSemiconductor/pc-nrfconnect-serial-terminal, pull requests merged in 2024-10, with the labels that each got.

#85 Update Shared with fixes
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#86 Fix: Regression with cli auto connect for devices with persisted data
  package-lock.json
  package.json
Labels: doc not required, ui not required

#87 Update changelog for the 1.4.2 release
  Changelog.md
Labels: doc not required, ui not required

#89 tooltips: review style and phrasing
  src/components/DeviceSelector.tsx
  src/components/Terminal/Main.tsx
  src/components/Terminal/SerialSettings/index.tsx
  src/components/Terminal/Terminal.tsx
  src/components/Terminal/TerminalSettings/ExportLog.tsx
  src/components/Terminal/TerminalSettings/index.tsx
Labels: doc required, ui required

#88 doc: update for Serial Terminal v1.4.2
  doc/docs/connecting.md
  doc/docs/installing.md
  doc/docs/overview.md
  doc/docs/revision_history.md
  doc/docs/screenshots/serial_term_connect_to_port.png
  doc/docs/screenshots/serial_term_select_device.png
  doc/docs/screenshots/serial_term_serial_ports.png
  doc/docs/screenshots/serial_term_startup.png
  doc/docs/selecting_serial_port.md
  doc/mkdocs.yml
Labels: documentation, doc required

#90 Update shared to v188 and nrfutil device to v2.6.4
  Changelog.md
  package-lock.json
  package.json
Labels: doc required, ui not required

#91 Renovate/use dropdown helpers from shared
  package-lock.json
  package.json
  src/components/Terminal/SerialSettings/Baudrate.tsx
  src/components/Terminal/SerialSettings/index.tsx
  src/components/Terminal/TerminalSettings/index.tsx
  src/utils/dataConstructors.ts
Labels: doc not required, ui not required

#93 fix: ensure that terminal gets resized during startup
  src/hooks/useFitAddon.ts
Labels: doc not required, ui not required
